
import { Product, Category, Recipe, SubCategory } from './types';

export const CATEGORIES: Category[] = [
  { id: 'pantry', name: 'Abarrotes', icon: '🍞', color: 'bg-yellow-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767905244/Abarrotes_bcpucm.jpg' },
  { id: 'birds', name: 'Aves', icon: '🍗', color: 'bg-orange-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767904069/Aves_fxtyoh.jpg' },
  { id: 'drinks', name: 'Bebidas', icon: '🥤', color: 'bg-purple-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767906877/bebidas_fnb4gz.jpg' },
  { id: 'frozen', name: 'Congelados', icon: '🧊', color: 'bg-cyan-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767907949/Congelados_zsadzt.png' },
  { id: 'personal-care', name: 'Cuidado Personal', icon: '🧴', color: 'bg-pink-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767908268/Cuidado_Personal_uwc56v.png' },
  { id: 'fruits', name: 'Frutas y Verduras', icon: '🍎', color: 'bg-red-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767903164/frutas_y_Verduras_xvvee3.png' },
  { id: 'dairy', name: 'Lácteos y Huevos', icon: '🥛', color: 'bg-blue-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767904631/Lacteos_y_huevos_vsd2c1.jpg' },
  { id: 'cleaning', name: 'Limpieza', icon: '🧼', color: 'bg-green-50', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767907401/Bebidas_ph8krf.png' },
  {id: 'hyb', name: 'Hogar y Bazar', icon: '🛋️', color: 'bg-pink-50', image: '' },
  {id: 'meats', name: 'Carnes', icon: '🥩', color: 'bg-cyan-50', image: '' },
  {id: 'cigarettes', name: 'Cigarrillos', icon: '🚬', color: 'bg-gray-50', image: '' },
  {id: 'prepared-foods', name: 'Comida Preparadas', icon: '🍱', color: 'bg-orange-50', image: '' },
  {id: 'deli', name: 'Embutidos y Delicatessen', icon: '🧀', color: 'bg-rose-50', image: '' },
  {id: 'flowers-garden', name: 'Flores y Jardín', icon: '🌷', color: 'bg-green-50', image: '' },
  {id: 'toys-games', name: 'Juegos y Juguetes', icon: '🧸', color: 'bg-purple-50', image: '' },
  {id: 'pets', name: 'Mascotas', icon: '🐾', color: 'bg-amber-50', image: '' },
  {id: 'kids-babies', name: 'Niños y Bebés', icon: '👶', color: 'bg-blue-50', image: '' },
  {id: 'bakery', name: 'Panaderia y Pasteleria', icon: '🍰', color: 'bg-yellow-50', image: '' },
  {id: 'stationery', name: 'Papeleria y Utiles Escolares', icon: '✏️', color: 'bg-blue-50', image: '' },
  {id: 'grill-outdoor', name: 'Parrilla y Aire Libre', icon: '🔥', color: 'bg-orange-50', image: '' },
  {id: 'seafood', name: 'Pescados y Mariscos', icon: '🐟', color: 'bg-blue-50', image: '' },
  {id: 'wine-spirits', name: 'Vino y Licores', icon: '🍷', color: 'bg-purple-50', image: '' },
];

export const PRODUCTS: Product[] = [
  { id: '1', name: 'Cerveza Club Premium Planino Six', price: 5.65, originalPrice: 8.11, discount: 30, category: 'drinks', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767908728/Club_zomcfp.jpg', badge: 'Oferta', unit: '330 ML' },
  { id: '2', name: 'Leche UHT Entera Nutri 1LT', price: 1.19, category: 'dairy', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767973418/LecheEnteraNutri_ciwfqu.jpg', unit: 'unidad', isBestSeller: true },
  { id: '3', name: 'Grano Lentejon La Cena', price: 1.05, originalPrice: 1.40, discount: 25, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767909032/lentejaLaCena_enmvqf.jpg', unit: '450 GR' },
  { id: '4', name: 'Arroz Delportal 2kg', price: 2.41, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767993947/ArrozDelportal_beopox.jpg', unit: 'bolsa', isRecommended: true },
  { id: '5', name: 'Huevo BIO Empacados Grandes', price: 3.09, originalPrice: 6.17, discount: 50, category: 'dairy', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767909517/HuevosBio_hwsyf3.jpg', badge: 'Más Vendido', unit: 'X30', isBestSeller: true },
  { id: '6', name: 'Vino Tinto Malbec Los Cardos Doña Paula Arg.', price: 10.86, category: 'drinks', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767994080/VinoTMalbec_ml2mrt.jpg', unit: 'botella', isRecommended: true },
  { id: '7', name: 'Aguacate Fuerte UND', price: 1.65, category: 'fruits', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767994257/Aguacate_tsxq2p.jpg', unit: 'Libra', isBestSeller: true },
  { id: '8', name: 'Detergente Polvo Limon Deja 2kg', price: 4.81, category: 'cleaning', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767994505/Deja_moldpb.jpg', unit: '2 KG' },
  { id: '9', name: 'Pulpa Congelada Maracuya Natutropic', price: 2.72, originalPrice: 3.02, discount: 10, category: 'frozen', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767969690/PulpaCongeladaMaracuya_auxaa3.jpg', badge: 'Oferta', unit: '500 GR' },
  { id: '10', name: 'Tomate Cherry Organico Ochoberries', price: 2.46, originalPrice: 2.89, discount: 30, category: 'fruits', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768231149/tomatesCherry_owisq3.jpg', badge: 'Oferta', unit: '300 G' },
  { id: '11', name: 'Lomo Fino de Res', price: 43.96, category: 'meats', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768248509/LomofinoDeres_duee7k.jpg', unit: 'Aproximadamente 4.00 libra(s) por unidad.' },
  { id: '12', name: 'Ajo con Cascara Empacado', price: 1.21, category: 'fruits', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768248933/Ajo_xpeose.jpg', unit: '250 GR.' },
  { id: '13', name: 'Cebolla Perla Und', price: 0.26, category: 'fruits', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768249274/cebollaperla_upb0jl.jpg', unit: 'Aproximadamente 2.75 unidad(es) por libra.' },
  { id: '14', name: 'Aceite Vegetal Girasol Delportal', price: 2.79, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768249447/aceitevegdelportal_yp6dtt.jpg', unit: '1 LT.' },
  { id: '15', name: 'Harina de Trigo YA Funda', price: 1.12, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768249562/harinadetrigo_nmkd7i.jpg', unit: '500 GR.' },
  { id: '16', name: 'Perefil Atado', price: 0.66, category: 'fruits', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768249879/perejil_idwzkc.jpg', unit: '' },
  { id: '17', name: 'Comino molido El Sabor Funda', price: 1.17, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768250054/comino_zy0e73.jpg', unit: '50 GR.' },
  { id: '18', name: 'Paprika', price: 2.81, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768250219/paprika_bcokrb.jpg', unit: '50 G.' },
  { id: '19', name: 'Jugo de tomate CIRIO', price: 1.13, category: 'drinks', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768250305/Jugo_de_Tomate_cvr8sw.jpg', unit: '200 GR.' },
  { id: '20', name: 'Queso Mozzarella Kiosko', price: 2.39, category: 'dairy', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768250426/queso_mozzarella_t9sbci.jpg', unit: '200 GR' },
  { id: '21', name: 'Tortillas Rapiditas Cero Cero', price: 2.39, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768250607/tortillas_egtfqd.jpg', unit: '250 GR.' },
  { id: '22', name: 'Atún en Aceite Girasol Real', price: 1.55, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768251645/atun_fwfsmy.jpg', unit: '160 GR.' },
  { id: '23', name: 'Tomate Riñon Malla', price: 0.99, category: 'fruits', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768252013/tomate_zbfqzk.jpg', unit: '1000 GR' },
  { id: '24', name: 'Maiz Dulce Facundo', price: 2.16, category: 'frozen', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768252408/maiz_dulce_zoqhws.jpg', unit: '500 GR.' },
  { id: '25', name: 'Mayonesa Los Andes Sachet', price: 0.50, category: 'pantry', image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1768252494/mayonesa_prk7us.jpg', unit: '8 GR.' },
];

export const SUBCATEGORIES: SubCategory[] = [
  { id: 'oil', name: 'Aceites', categoryId: 'pantry' },
  { id: 'grains', name: 'Arroz y Granos', categoryId: 'pantry' },
  { id: 'sugar', name: 'Azúcar y Sustitutos', categoryId: 'pantry' },
  { id: 'cacao', name: 'Cacao y Derivados', categoryId: 'pantry' },
  { id: 'coffee', name: 'Café y Sustitutos', categoryId: 'pantry' },
  { id: 'infusions', name: 'Café e Infusiones', categoryId: 'pantry' },
  { id: 'cereals', name: 'Cereales', categoryId: 'pantry' },
  { id: 'candies', name: 'Chicles, Caramelos y Gomitas', categoryId: 'pantry' },
  { id: 'instant', name: 'Comida Instantánea', categoryId: 'pantry' },
  { id: 'refrigerated', name: 'Comida Refrigerada', categoryId: 'pantry' },
  { id: 'canned', name: 'Conservas y Enlatados', categoryId: 'pantry' },
  { id: 'dips', name: 'Dips', categoryId: 'pantry' },
  { id: 'pasta', name: 'Fideos y Pastas', categoryId: 'pantry' },
  { id: 'cookies', name: 'Galletas', categoryId: 'pantry' },
  { id: 'jam', name: 'Mermeladas y Jaleas', categoryId: 'pantry' },
  { id: 'baking', name: 'Repostería y Gelatinas', categoryId: 'pantry' },
  { id: 'milk-flavor', name: 'Saborizantes de Leche', categoryId: 'pantry' },
  { id: 'sauces', name: 'Salsas y Aderezos', categoryId: 'pantry' },
  { id: 'snacks', name: 'Snacks', categoryId: 'pantry' },
  { id: 'nuts', name: 'Snacks y Frutos Secos', categoryId: 'pantry' },

  { id: 'pork', name: 'Cerdo', categoryId: 'meats' },
  { id: 'cbc', name: 'Chivo, Borrego, Cordero', categoryId: 'meats' },
  { id: 'Cimports', name: 'Cortes Importados', categoryId: 'meats' },
  { id: 'cow', name: 'Res', categoryId: 'meats' },

  { id: 'mend', name: 'Menudencia de Pollo', categoryId: 'birds' },
  { id: 'turkey', name: 'Pavos', categoryId: 'birds' },
  { id: 'allchick', name: 'Pollo Completo', categoryId: 'birds' },
  { id: 'vaciopollo', name: 'Pollo Vacio', categoryId: 'birds' },
  { id: 'presapoll', name: 'Presa de Pollo', categoryId: 'birds' },
  { id: 'presa', name: 'Presas', categoryId: 'birds' },

  { id: 'water', name: 'Agua', categoryId: 'drinks' },
  { id: 'hotdrink', name: 'Bebidas Calientes', categoryId: 'drinks' },
  { id: 'healtydrink', name: 'Bebidas Saludables', categoryId: 'drinks' },
  { id: 'soda', name: 'Gaseosas', categoryId: 'drinks' },
  { id: 'H&E', name: 'Hidratantes y Energizantes', categoryId: 'drinks' },
  { id: 'juicenature', name: 'Jugos 100% Naturales', categoryId: 'drinks' },
  { id: 'otherdrinks', name: 'Jugos y Otras bebidas', categoryId: 'drinks' },

  { id: 'BMP', name: 'Bocaditos, Masas y Pasta', categoryId: 'frozen' },
  { id: 'foodice', name: 'Comida Congelada', categoryId: 'frozen' },
  { id: 'fruitvegetice', name: 'Frutas y Verduras Congeladas', categoryId: 'frozen' },
  { id: 'icecream', name: 'Helados', categoryId: 'frozen' },
  { id: 'ice', name: 'Hielo', categoryId: 'frozen' },
  { id: 'licorice', name: 'Licor Congelado', categoryId: 'frozen' },
  { id: 'ps', name: 'Pastas y Salsas', categoryId: 'frozen' },
  
  { id: 'cma', name: 'Crema, Maquillaje y Accesorios', categoryId: 'personal-care' },
  { id: 'cbucal', name: 'Cuidado bucal', categoryId: 'personal-care' },
  { id: 'ccapilar', name: 'Cuidado Capilar', categoryId: 'personal-care' },
  { id: 'ccorporal', name: 'Cuidado Corporal', categoryId: 'personal-care' },
  { id: 'cfemenino', name: 'Cuidado Femenino', categoryId: 'frozen' },
  { id: 'cmasculino', name: 'Cuidado Masculino', categoryId: 'personal-care' },
  { id: 'pharmacy', name: 'Farmacia', categoryId: 'personal-care' },
  { id: 'proteccion', name: 'Protección Incontinencia', categoryId: 'personal-care' },

  { id: 'fruit', name: 'Frutas', categoryId: 'fruits' },
  { id: 'organic', name: 'Organicos', categoryId: 'fruits' },
  { id: 'vegetables', name: 'Vegetales y Verduras', categoryId: 'fruits' },

  { id: 'egg', name: 'Huevos', categoryId: 'dairy' },
  { id: 'milk', name: 'Leches', categoryId: 'dairy' },
  { id: 'butter', name: 'Mantequillas y Margarinas', categoryId: 'dairy' },
  { id: 'cheese', name: 'Quesos', categoryId: 'dairy' },
  { id: 'yogur', name: 'Yogurt', categoryId: 'dairy' },

  { id: 'cropa', name: 'Cuidado de Ropa', categoryId: 'cleaning' },
  { id: 'hbaño', name: 'Higiene de Baños', categoryId: 'cleaning' },
  { id: 'lcarro', name: 'Limpieza de Automóviles', categoryId: 'cleaning' },
  { id: 'lcocina', name: 'Limpieza de Cocina', categoryId: 'cleaning' },
  { id: 'lcalzado', name: 'Limpieza del Calzado', categoryId: 'cleaning' },
  { id: 'lhome', name: 'Limpieza y Cuidado del Hogar', categoryId: 'cleaning' },

  { id: 'autom', name: 'Automotriz', categoryId: 'hyb' },
  { id: 'cocinya', name: 'Cocina y Accesorios', categoryId: 'hyb' },
  { id: 'decoration', name: 'Decoracion', categoryId: 'hyb' },
  { id: 'desch', name: 'Desechables', categoryId: 'hyb' },
  { id: 'party', name: 'Fiesta', categoryId: 'hyb' },
  { id: 'focosypilas', name: 'Focos y Pilas', categoryId: 'hyb' },
  { id: 'iconypila', name: 'Icono y Pilas', categoryId: 'hyb' },
  { id: 'hbaño', name: 'Higiene de Baños', categoryId: 'hyb' },
  { id: 'lcarro', name: 'Limpieza de Automóviles', categoryId: 'hyb' },
  { id: 'cristmas', name: 'Navidad', categoryId: 'hyb' },
  { id: 'organitation', name: 'Organización', categoryId: 'hyb' },
  { id: 'tecnology', name: 'Tecnología', categoryId: 'hyb' },

  { id: 'cigarette', name: 'Cigarrillo', categoryId: 'cigarettes' },

  { id: 'preparedfood', name: 'Comidas Preparadas', categoryId: 'prepared-foods' },

  { id: 'embupeso', name: 'Embutidos al Peso', categoryId: 'deli' },
  { id: 'embupack', name: 'Embutidos Empacados', categoryId: 'deli' },
  { id: 'burguer', name: 'Hamburguesas', categoryId: 'deli' },
  { id: 'valoragg', name: 'Valor Agregado', categoryId: 'deli' },
  { id: 'others', name: 'Varios', categoryId: 'deli' },

  { id: 'arrflower', name: 'Bouquet y Arreglos Florales', categoryId: 'flowers-garden' },
  { id: 'envase', name: 'Envases', categoryId: 'flowers-garden' },
  { id: 'flower', name: 'Flores', categoryId: 'flowers-garden' },
  { id: 'gardem', name: 'Jardinería', categoryId: 'flowers-garden' },

  { id: 'games', name: 'Juegos', categoryId: 'toys-games' },
  { id: 'toys', name: 'Juguetes', categoryId: 'toys-games' },
  
  { id: 'accesoriespets', name: 'Accesorios', categoryId: 'pets' },
  { id: 'otheralimentspet', name: 'Otros Alimentos', categoryId: 'pets' },
  { id: 'forcat', name: 'Para Gatos', categoryId: 'pets' },
  { id: 'hamster', name: 'Para Hamster', categoryId: 'pets' },
  { id: 'fordog', name: 'Para Perros', categoryId: 'pets' },

  { id: 'accesoriesbaby', name: 'Accesorios Bebes', categoryId: 'kids-babies' },
  { id: 'alimentsbaby', name: 'Alimentacion', categoryId: 'kids-babies' },
  { id: 'babycare', name: 'Aseo y Cuidado del Bebé', categoryId: 'kids-babies' },
  { id: 'toysbaby', name: 'La Juguetería', categoryId: 'kids-babies' },
  { id: 'babywordl', name: 'Mundo Bebé', categoryId: 'kids-babies' },
  { id: 'pañales', name: 'Pañales y Toallitas Húmedas', categoryId: 'kids-babies' },

  { id: 'cakespack', name: 'Cakes y Bocaditos empacados', categoryId: 'bakery' },
  { id: 'dips', name: 'Dips', categoryId: 'bakery' },
  { id: 'disytor', name: 'Discos y Tortillas', categoryId: 'bakery' },
  { id: 'thebakery', name: 'La Panaderia', categoryId: 'bakery' },
  { id: 'masamother', name: 'Masa Madre', categoryId: 'bakery' },
  { id: 'indbakery', name: 'Panaderia Industrial', categoryId: 'bakery' },
  { id: 'bakerysweet', name: 'Pasteleria y Dulceria', categoryId: 'bakery' },
  { id: 'frozeenbakery', name: 'Postre Congelados', categoryId: 'bakery' },
  { id: 'precocid', name: 'Precocido', categoryId: 'bakery' },
  { id: 'reyesrosca', name: 'Rosca de Reyes', categoryId: 'bakery' },
  { id: 'saludable', name: 'Saludable', categoryId: 'bakery' },

  { id: 'school', name: 'Papeleria y Temporada Escolar', categoryId: 'stationery' },

  { id: 'grill', name: 'Parrillas', categoryId: 'grill-outdoor' },
  { id: 'beach', name: 'Playa y Piscina', categoryId: 'grill-outdoor' },

  { id: 'seafoodfrozen', name: 'Mariscos Congelados', categoryId: 'seafood' },

  { id: 'beer', name: 'Cervezas', categoryId: 'wine-spirits' },
  { id: 'espumantes', name: 'Champagne, Espumantes y Cavas', categoryId: 'wine-spirits' },
  { id: 'coktail', name: 'Cocteles', categoryId: 'wine-spirits' },
];

export const RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Quesa Birria',
    description: 'Una opción fresca, rápida y saludable para toda la familia con ingredientes de nuestro portal.',
    image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767990382/QuesaBirria_erzyjz.jpg',
    ingredients: ['4, 40 lb de lomo fino', '1 cebolla perla grande', '3 dientes de ajo', 'Sal y pimienta', 'Aceite Vegetal', 'Harina de Trigo', 'Caldo de carne', 'Perejil', 'Comino', 'Paprika', 'Jugo de tomate', 'Queso mozzarella', 'Tortillas'],
    productIds: ['11', '13', '12', '14', '15', '16', '17', '18', '19', '20', '21'],
    prepTime: '45 min',
    difficulty: 'Media',
    steps: ['En una olla grande a fuego medio, calienta 2 cucharadas de aceite y sofríe la cebolla picada finamente y 3 dientes de ajo picados fiamente hasta que estén bien pochados.',
    'Agrega el lomo fino cortado en trozos medianos y sazonar con sal y pimienta al gusto. Deja cocinar por 10 minutos.',
    'Después agrega 1/2 taza de harina y sofríe por unos minutos más.',
    'Agrega 2 tazas de caldo de carne, 1/2 taza de jugo de tomate y 1/4 de taza de agua, y mezcla todos los ingredientes bien.',
    'Agrega 2 cucharadas de Perejil picado, 2 cucharadas de Comino molido, cilantro, y 2 cucharadas de Paprika, mezcla todo bien y deja cocinar por 25 minutos con fuego bajo y deja que se forme una salsa.',
    'Para servir, extiende una tortilla y agrega la carne en su salsa, luego adorna con queso Oaxaca.',
    'Realiza los tacos y deja calentar al fuego o a la sartén los tacos recién hechos.',
    '¡Tú quesa birria esta lista para servir! ¡Disfruta!'
    ]
  },
  {
    id: 'r2',
    title: 'Aguacates Rellenos de Atún',
    description: 'El clásico de los hogares ecuatorianos con el toque de frescura Delportal.',
    image: 'https://res.cloudinary.com/dilzkmcsl/image/upload/v1767991951/AguacatesRellenos_jbupve.jpg',
    ingredients: ['2 latas de atún', '2 aguacates', '1 tomate', '1 lata de maíz dulce', 'Sal', 'Perejil', 'Mayonesa'],
    productIds: ['22', '7', '23', '24', '16', '25'],
    prepTime: '15 min',
    difficulty: 'Fácil',
    steps: 
    [ 'Vaciar en un recipiente el atún con un poquito de aceite de oliva y revolver.',
    'Cortar en cuadritos el tomate, añadir el maíz, el perejil y poner todo en un tazón con mayonesa al gusto.',
    'Cortar el aguacate por la mitad y extraer el hueso y hacer un poco de espacio para la mezcla.',
    'Mezclar el atún con los demás ingredientes.',
    'Rellenar los aguacates con la mezcla y listo.'
    ]
  }
];
